language: php

php:
  - 7.1
  - 7.3

before_script:
  - travis_retry composer self-update
  - composer require satooshi/php-coveralls
  - travis_retry composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate

script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
after_script:
  - travis_retry php vendor/bin/php-coveralls
  - travis_retry php vendor/bin/php-coveralls -v
